### ISSUE TITLE
[BUG] Module filelock don't have attribute 'logger'

### ISSUE THREAD

**Issue by VoXaN24** [Progeny42/refrapt#8]
I've install it with pip, it don't work with the last version of Ubuntu and Python

![image](https://user-images.githubusercontent.com/30030208/143587224-7cabc472-99d6-40ae-94d7-30df3a06790b.png)

**Comment by Progeny42** [comment]
It appears filelock has had an overhaul since refrapt was published, which altered the API. refrapt does not need these updates, so for now, a minor version changes has been made which enforces the version of filelock that does work.

You will need to uninstall refrapt, and then reinstall in order to get version 0.2.2. This should address your issue.

**Comment by VoXaN24** [comment]
It work thank's !
